# Generated by Django 4.1.2 on 2022-10-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fechanacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('celular', models.CharField(max_length=25)),
            ],
        ),
    ]
